/* NOTE this file is autogenerated by Scalate : see http://scalate.fusesource.org/ */
package src.main.scalate.com.juke.views

import _root_.scala.collection.JavaConversions._
import _root_.org.fusesource.scalate.support.TemplateConversions._
import _root_.org.fusesource.scalate.util.Measurements._

object $_scalate_$NotFoundError_ssp {
  def $_scalate_$render($_scalate_$_context: _root_.org.fusesource.scalate.RenderContext): Unit = {
    ;{
      val helper: xitrum.Action = $_scalate_$_context.attribute("helper")
      import helper._
      ;{
        val context: org.fusesource.scalate.RenderContext = $_scalate_$_context.attribute("context")
        import context._
        
        
        import         com.juke.views

        $_scalate_$_context << ( "\n\n<html>\n\t<head>\n\t\t<title> JUKE - Not found! </title>\n\t</head>\n\t<body>\n\t\t404 - Not Found\n\t</body>\n</html>\n" );
      }
    }
  }
}


class $_scalate_$NotFoundError_ssp extends _root_.org.fusesource.scalate.Template {
  def render(context: _root_.org.fusesource.scalate.RenderContext): Unit = $_scalate_$NotFoundError_ssp.$_scalate_$render(context)
}
